# Generated by Django 2.2.7 on 2019-11-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents', models.ManyToManyField(to='main.Category', verbose_name='Parents')),
            ],
        ),
    ]
