# Generated by Django 2.2.7 on 2019-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parents',
        ),
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='main.Category', verbose_name='children'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=512, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
    ]
