# Generated by Django 2.2.7 on 2019-11-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191113_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.Category', verbose_name='parent'),
        ),
    ]
